### ISSUE TITLE
knxd master is not the right one to use

### ISSUE THREAD

**Issue by tru7** [linknx/install#1]
in your script you use this
```
git clone https://github.com/knxd/knxd.git
mv knxd-master knxd
cd knxd
```
you should use stable branch (git checkout stable) instead. This is currently v0.12 which does not use pthsem anymore but has a dependency on libev, libev-dev. You cannot rely on master branch.

**Comment by energy01** [comment]
i fixed the bug thanks
with #

**Comment by energy01** [comment]
#https://github.com/linknx/install/commit/2275de730a98159e3b9aa4d34b3adc93f318d33c
